using System.ComponentModel.DataAnnotations.Schema;
using wdb_backend.Common;

namespace wdb_backend.Models;

/// <summary>
/// Represents a permission in the system. Maps to the "permission" table in the database.
/// </summary>
[Table("permission")]
public class Permission
{
    /// <summary>
    /// Unique identifier (UUID), auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key referencing the information being requested.
    /// </summary>
    [Column("info_id")]
    public Guid InfoId { get; set; }

    /// <summary>
    /// Foreign key referencing the worker whose data is being requested.
    /// </summary>
    [Column("worker_id")]
    public Guid WorkerId { get; set; }

    /// <summary>
    /// Foreign key referencing the request which this belongs to.
    /// </summary>
    [Column("request_id")]
    public Guid RequestId { get; set; }

    /// <summary>
    /// Timestamp of when the record was updated by the status. Auto-generated by the database.
    /// </summary>
    [Column("last_updated_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime LastUpdatedAt { get; set; }

    /// <summary>
    /// Timestamp of when the permission expires.
    /// </summary>
    [Column("expiry_date")]
    public DateTime? ExpiryDate { get; set; }

    /// <summary>
    /// The permission's status such as pending/approved/rejected.
    /// </summary>
    [Column("status")]
    public required PermissionStatus Status { get; set; }

    public Request Request { get; set; }

    public WorkerInfo WorkerInfo { get; set; }
}
