using System.ComponentModel.DataAnnotations.Schema;

namespace wdb_backend.Models;

/// <summary>
/// Represents a request in the system. Maps to the "request" table in the database.
/// </summary>
[Table("request")]
public class Request
{
    /// <summary>
    /// Unique identifier (UUID), auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key referencing the employer who submitted the request.
    /// </summary>
    [Column("employer_id")]
    public Guid EmployerId { get; set; }

    /// <summary>
    /// Foreign key referencing the worker whose data is been requested.
    /// </summary>
    [Column("worker_id")]
    public Guid WorkerId { get; set; }

    /// <summary>
    /// Timestamp of when the record was created. Auto-generated by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// The reason for why the employer submits a request.
    /// </summary>
    [Column("reason")]
    public required string Reason { get; set; }

    public WorkerInfo WorkerInfo { get; set; }
    public Worker Worker { get; set; }
    public List<Permission> Permissions { get; set; }
}
